### ISSUE TITLE
[Bug] Deprecation of scipy.sparse.coo_matrix.A in scipy 1.14

### ISSUE THREAD

**Issue by jo460464** [NeuralEnsemble/elephant#644]
**Describe the bug**
Running spade produces AttributeError

**To Reproduce**
1.  run elephant.spade.spade with scipy 1.14

 AttributeError: 'coo_matrix' object has no attribute 'A'

**Expected behavior**

**Environment**
 - OS (e.g., Linux): Linux
 - How you installed elephant (`conda`, `pip`, source): pip
 - Python version: 3.10
 - `neo` python package version: 0.13.3
 - `elephant` python package version: 1.1
 - (Any additional python package you want to include here)

**Comment by Moritz-Alexander-Kern** [comment]
Hey @jo460464 ,
thanks for reporting this.
I think this might have already been addressed here:
See: https://github.com/NeuralEnsemble/elephant/pull/636

Try installing the latest development version of elephant with:

```bash
pip install git+ssh://git@github.com/NeuralEnsemble/elephant.git@main
```

**Comment by jo460464** [comment]
I am already at the most recent I think, is there a newer version than 1.1.0

**Comment by jo460464** [comment]
I mean I see that #636 describes my bug, but in my installation at least it is still present

**Comment by jo460464** [comment]
But in the problem seems to be local, thanks Moritz
